In [1]:
import joblib

In [3]:
mind = joblib.load('marks.pk1')

In [4]:
mind.coef_

array([10.])

In [6]:
avi = 7

In [7]:
mind.predict([[avi]])

array([70.])

In [8]:
import numpy as np

In [14]:
a = [[1,2,3],[4,5,6],[7,8,9],[10,11,12]]

In [15]:
type(a)

list

In [16]:
a=np.array(a)

In [17]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [18]:
type(a)

numpy.ndarray

In [26]:
a[1:4,1]

array([ 5,  8, 11])

In [27]:
a.shape

(4, 3)

In [36]:
a.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])